spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres@tf-db.cmxfpu2rrcpx.us-east-1.rds.amazonaws.com}:${POSTGRES_PORT:5432}/${POSTGRES_DB:tf-db?schema=public}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
